select * from employees;
select first_name ,last_name from employees;
select first_name ,salary from employees where hire_date between '01-01-2005' and '31-12-2005';
select first_name from employees where first_name like 'N%';
select *from employees where salary <5000;
select * from employees where department_id in (10,30,110,80);
select * from employees where commission_pct is null;
select * from employees where hire_date = '21-09-2005';
select * from employees where hire_date between '01-01-2005' and '31-01-2007';
select * from employees where first_name like 'S%' and  length(salary)>4;
select * from (select first_name,salary,dense_rank()over(order by salary desc)as  r from employees )where r=1;
select round(avg(salary)) from employees;
select first_name from employees group by first_name having count(first_name)>1;
select * from (select first_name,salary ,dense_rank()over(partition by department_id order by salary desc )as r from employees )where r=1;
select * from (select first_name,salary,dense_rank()over(partition by department_id order by salary desc)as r from employees )where r=1 and salary>10000;
select * from (select first_name ,salary ,dense_rank()over(order by salary desc )as r from employees )where r=1 and first_name like 'S%';
select * from employees where salary >(select avg(salary)from employees) ;
select avg(salary) from employees where hire_date > '01-01-2005';
select sum(salary) from employees group by department_id;
select max(salary) from employees where first_name ='Peter';
select * from employees where salary>(select avg(salary) from employees);
select * from employees where manager_id =(select manager_id from employees where first_name ='Bruce');
select d.department_name ,(select locations.city from locations where locations.location_id=d.location_id)from departments d;
select * from (select first_name,salary,dense_rank()over(order by salary desc)as r from employees) where r=5;
select * from employees where department_id=(select department_id from employees where first_name ='Stephen');
select * from employees where manager_id =( select employee_id from employees where first_name ='Nancy');
select * from employees where to_char( hire_date,'mon')='feb';
select  * from employees where to_char(hire_date,'dy')='mon';
select * from employees where months_between(sysdate,hire_date)/12>17;
select * from user_tables;
select * from employees where department_id is null;
select d.department_id ,e.first_name from employees e left join departments d on e.department_id =d.department_id  where d.department_id is null; 
select count(order_id),cust_id from order_table group by cust_id;
desc cust_table;
desc order_table;
desc shipment_table;
select count(o.order_id),c.cust_name from order_table o join cust_table c on c.cust_id =o.cust_id group by c.cust_name;
select  distinct p.prod_name ,o.cust_id from prod_table p join order_table o on p.prod_id=o.prod_id order by cust_id asc;
select e.salary,d.department_id from employees e join departments d on e.department_id =d.department_id join (select avg(salary)as avg_sal ,department_id from employees group by department_id ) dept on dept.department_id=e.department_id where e.salary>dept.avg_sal ;
select sum(p.amount),o.salesperson_id from order_table o join prod_table p on p.prod_id=o.prod_id group by salesperson_id;
select count(cust_id),prod_id from order_table group by prod_id;
select p.prod_name from prod_table p left join order_table o on p.prod_id =o.prod_id where o.order_id is null;
select avg(salary),department_id from employees group by department_id ;
select count(o.order_id) from order_table o full join shipment_table s on o.delivery_date =s.delivery_date where s.delivery_date is  null;
select * from shipment_table;
select e.first_name ,m.first_name from employees e join employees m on e.employee_id =m.manager_id;
select * from (select first_name,salary,dense_rank()over(order by salary desc)as r from employees) where r=2;
select * from employees where hire_date between '01-01-2003' and '31-12-2003';
select count(*) from employees group by department_id ;
select * from employees where first_name like 'A%';
select first_name from employees group by first_name having count(first_name )>1;
delete from emp1 where rowid not in (select max(rowid) from emp1 group by name);
desc emp1;
insert into emp1 values(100,'sundar','salem','098765','chennai');
select * from emp1;
select * from employees where rownum<=3;
select * from employees where department_id is null;
select * from employees where salary between 20000 and 30000;
select count(e.employee_id ) ,d.department_name from departments d join employees  e on e.department_id=d.department_id group by d.department_name ;
select current_date,current_timestamp from dual ;
select count(*) from employees where commission_pct is null;
update  employees set salary =salary*1.10 where employees.employee_id = 100; 
alter table emp1 rename column address to city1 ;
alter table emp1 add city3 varchar(30);
alter table emp1 modify city3 varchar2(40);
alter table emp1 drop column city3;
select first_name,salary,
    case when salary>=10000 then 'hight'
     when salary =10000 then 'mid'
     when salary <=10000 then 'low'
    end 
     from employees;
create view v300 as select * from emp1;
select first_name,commission_pct ,nvl2(commission_pct,100,200) from employees;